/*
* generated by Xtext
*/
package org.xtext.example.mydsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Activity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActivityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cPeriodiciteKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPeriodiciteAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPeriodicitePeriodiciteEnumRuleCall_2_1_0 = (RuleCall)cPeriodiciteAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActivitesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActivitesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cActivitesActivitesEnumRuleCall_3_1_0 = (RuleCall)cActivitesAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAtelierKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAtelierAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cAtelierAtelierCrossReference_4_2_0 = (CrossReference)cAtelierAssignment_4_2.eContents().get(0);
		private final RuleCall cAtelierAtelierEStringParserRuleCall_4_2_0_1 = (RuleCall)cAtelierAtelierCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cAtelierAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cAtelierAtelierCrossReference_4_3_1_0 = (CrossReference)cAtelierAssignment_4_3_1.eContents().get(0);
		private final RuleCall cAtelierAtelierEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cAtelierAtelierCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRes_allocKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRes_allocAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRes_allocRes_AllocParserRuleCall_5_2_0 = (RuleCall)cRes_allocAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cRes_allocAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cRes_allocRes_AllocParserRuleCall_5_3_1_0 = (RuleCall)cRes_allocAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRuleKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRuleAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cRuleRuleParserRuleCall_6_2_0 = (RuleCall)cRuleAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRuleAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cRuleRuleParserRuleCall_6_3_1_0 = (RuleCall)cRuleAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cFinKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cFinAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cFinDateParserRuleCall_8_0 = (RuleCall)cFinAssignment_8.eContents().get(0);
		private final Keyword cDebutKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDebutAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDebutDateParserRuleCall_10_0 = (RuleCall)cDebutAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Activity:
		//	("Activity" "{" ("periodicite" periodicite=Periodicite)? ("activites" activites=Activites) ("atelier" "("
		//	atelier+=[exploitation::Atelier|EString] ("," atelier+=[exploitation::Atelier|EString])* ")")? ("res_alloc" "{"
		//	res_alloc+=Res_Alloc ("," res_alloc+=Res_Alloc)* "}")? ("rule" "{" rule+=Rule ("," rule+=Rule)* "}")? "fin" fin=Date
		//	"debut" debut=Date "}")*;
		public ParserRule getRule() { return rule; }

		//("Activity" "{" ("periodicite" periodicite=Periodicite)? ("activites" activites=Activites) ("atelier" "("
		//atelier+=[exploitation::Atelier|EString] ("," atelier+=[exploitation::Atelier|EString])* ")")? ("res_alloc" "{"
		//res_alloc+=Res_Alloc ("," res_alloc+=Res_Alloc)* "}")? ("rule" "{" rule+=Rule ("," rule+=Rule)* "}")? "fin" fin=Date
		//"debut" debut=Date "}")*
		public Group getGroup() { return cGroup; }

		//"Activity"
		public Keyword getActivityKeyword_0() { return cActivityKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("periodicite" periodicite=Periodicite)?
		public Group getGroup_2() { return cGroup_2; }

		//"periodicite"
		public Keyword getPeriodiciteKeyword_2_0() { return cPeriodiciteKeyword_2_0; }

		//periodicite=Periodicite
		public Assignment getPeriodiciteAssignment_2_1() { return cPeriodiciteAssignment_2_1; }

		//Periodicite
		public RuleCall getPeriodicitePeriodiciteEnumRuleCall_2_1_0() { return cPeriodicitePeriodiciteEnumRuleCall_2_1_0; }

		//"activites" activites=Activites
		public Group getGroup_3() { return cGroup_3; }

		//"activites"
		public Keyword getActivitesKeyword_3_0() { return cActivitesKeyword_3_0; }

		//activites=Activites
		public Assignment getActivitesAssignment_3_1() { return cActivitesAssignment_3_1; }

		//Activites
		public RuleCall getActivitesActivitesEnumRuleCall_3_1_0() { return cActivitesActivitesEnumRuleCall_3_1_0; }

		//("atelier" "(" atelier+=[exploitation::Atelier|EString] ("," atelier+=[exploitation::Atelier|EString])* ")")?
		public Group getGroup_4() { return cGroup_4; }

		//"atelier"
		public Keyword getAtelierKeyword_4_0() { return cAtelierKeyword_4_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }

		//atelier+=[exploitation::Atelier|EString]
		public Assignment getAtelierAssignment_4_2() { return cAtelierAssignment_4_2; }

		//[exploitation::Atelier|EString]
		public CrossReference getAtelierAtelierCrossReference_4_2_0() { return cAtelierAtelierCrossReference_4_2_0; }

		//EString
		public RuleCall getAtelierAtelierEStringParserRuleCall_4_2_0_1() { return cAtelierAtelierEStringParserRuleCall_4_2_0_1; }

		//("," atelier+=[exploitation::Atelier|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//atelier+=[exploitation::Atelier|EString]
		public Assignment getAtelierAssignment_4_3_1() { return cAtelierAssignment_4_3_1; }

		//[exploitation::Atelier|EString]
		public CrossReference getAtelierAtelierCrossReference_4_3_1_0() { return cAtelierAtelierCrossReference_4_3_1_0; }

		//EString
		public RuleCall getAtelierAtelierEStringParserRuleCall_4_3_1_0_1() { return cAtelierAtelierEStringParserRuleCall_4_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }

		//("res_alloc" "{" res_alloc+=Res_Alloc ("," res_alloc+=Res_Alloc)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"res_alloc"
		public Keyword getRes_allocKeyword_5_0() { return cRes_allocKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//res_alloc+=Res_Alloc
		public Assignment getRes_allocAssignment_5_2() { return cRes_allocAssignment_5_2; }

		//Res_Alloc
		public RuleCall getRes_allocRes_AllocParserRuleCall_5_2_0() { return cRes_allocRes_AllocParserRuleCall_5_2_0; }

		//("," res_alloc+=Res_Alloc)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//res_alloc+=Res_Alloc
		public Assignment getRes_allocAssignment_5_3_1() { return cRes_allocAssignment_5_3_1; }

		//Res_Alloc
		public RuleCall getRes_allocRes_AllocParserRuleCall_5_3_1_0() { return cRes_allocRes_AllocParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("rule" "{" rule+=Rule ("," rule+=Rule)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"rule"
		public Keyword getRuleKeyword_6_0() { return cRuleKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//rule+=Rule
		public Assignment getRuleAssignment_6_2() { return cRuleAssignment_6_2; }

		//Rule
		public RuleCall getRuleRuleParserRuleCall_6_2_0() { return cRuleRuleParserRuleCall_6_2_0; }

		//("," rule+=Rule)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//rule+=Rule
		public Assignment getRuleAssignment_6_3_1() { return cRuleAssignment_6_3_1; }

		//Rule
		public RuleCall getRuleRuleParserRuleCall_6_3_1_0() { return cRuleRuleParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"fin"
		public Keyword getFinKeyword_7() { return cFinKeyword_7; }

		//fin=Date
		public Assignment getFinAssignment_8() { return cFinAssignment_8; }

		//Date
		public RuleCall getFinDateParserRuleCall_8_0() { return cFinDateParserRuleCall_8_0; }

		//"debut"
		public Keyword getDebutKeyword_9() { return cDebutKeyword_9; }

		//debut=Date
		public Assignment getDebutAssignment_10() { return cDebutAssignment_10; }

		//Date
		public RuleCall getDebutDateParserRuleCall_10_0() { return cDebutDateParserRuleCall_10_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class AtelierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Atelier");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAtelier_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cElevageParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCultureParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Atelier returns exploitation::Atelier:
		//	Atelier_Impl | Elevage | Culture;
		public ParserRule getRule() { return rule; }

		//Atelier_Impl | Elevage | Culture
		public Alternatives getAlternatives() { return cAlternatives; }

		//Atelier_Impl
		public RuleCall getAtelier_ImplParserRuleCall_0() { return cAtelier_ImplParserRuleCall_0; }

		//Elevage
		public RuleCall getElevageParserRuleCall_1() { return cElevageParserRuleCall_1; }

		//Culture
		public RuleCall getCultureParserRuleCall_2() { return cCultureParserRuleCall_2; }
	}

	public class Res_AllocElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Res_Alloc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRes_AllocAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRes_AllocKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDurationKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDurationAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDurationEIntegerObjectParserRuleCall_3_1_0 = (RuleCall)cDurationAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRes_typeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRes_typeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRes_typeResourceTypeParserRuleCall_4_1_0 = (RuleCall)cRes_typeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Res_Alloc:
		//	{Res_Alloc} "Res_Alloc" "{" ("duration" duration=EIntegerObject)? ("res_type" res_type=ResourceType)? "}";
		public ParserRule getRule() { return rule; }

		//{Res_Alloc} "Res_Alloc" "{" ("duration" duration=EIntegerObject)? ("res_type" res_type=ResourceType)? "}"
		public Group getGroup() { return cGroup; }

		//{Res_Alloc}
		public Action getRes_AllocAction_0() { return cRes_AllocAction_0; }

		//"Res_Alloc"
		public Keyword getRes_AllocKeyword_1() { return cRes_AllocKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("duration" duration=EIntegerObject)?
		public Group getGroup_3() { return cGroup_3; }

		//"duration"
		public Keyword getDurationKeyword_3_0() { return cDurationKeyword_3_0; }

		//duration=EIntegerObject
		public Assignment getDurationAssignment_3_1() { return cDurationAssignment_3_1; }

		//EIntegerObject
		public RuleCall getDurationEIntegerObjectParserRuleCall_3_1_0() { return cDurationEIntegerObjectParserRuleCall_3_1_0; }

		//("res_type" res_type=ResourceType)?
		public Group getGroup_4() { return cGroup_4; }

		//"res_type"
		public Keyword getRes_typeKeyword_4_0() { return cRes_typeKeyword_4_0; }

		//res_type=ResourceType
		public Assignment getRes_typeAssignment_4_1() { return cRes_typeAssignment_4_1; }

		//ResourceType
		public RuleCall getRes_typeResourceTypeParserRuleCall_4_1_0() { return cRes_typeResourceTypeParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRuleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRuleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPredicatKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cPredicatAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cPredicatPredicatCrossReference_3_2_0 = (CrossReference)cPredicatAssignment_3_2.eContents().get(0);
		private final RuleCall cPredicatPredicatEStringParserRuleCall_3_2_0_1 = (RuleCall)cPredicatPredicatCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cPredicatAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cPredicatPredicatCrossReference_3_3_1_0 = (CrossReference)cPredicatAssignment_3_3_1.eContents().get(0);
		private final RuleCall cPredicatPredicatEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cPredicatPredicatCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Rule:
		//	{Rule} "Rule" "{" ("predicat" "(" predicat+=[Predicat|EString] ("," predicat+=[Predicat|EString])* ")")? "}";
		public ParserRule getRule() { return rule; }

		//{Rule} "Rule" "{" ("predicat" "(" predicat+=[Predicat|EString] ("," predicat+=[Predicat|EString])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//{Rule}
		public Action getRuleAction_0() { return cRuleAction_0; }

		//"Rule"
		public Keyword getRuleKeyword_1() { return cRuleKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("predicat" "(" predicat+=[Predicat|EString] ("," predicat+=[Predicat|EString])* ")")?
		public Group getGroup_3() { return cGroup_3; }

		//"predicat"
		public Keyword getPredicatKeyword_3_0() { return cPredicatKeyword_3_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_3_1() { return cLeftParenthesisKeyword_3_1; }

		//predicat+=[Predicat|EString]
		public Assignment getPredicatAssignment_3_2() { return cPredicatAssignment_3_2; }

		//[Predicat|EString]
		public CrossReference getPredicatPredicatCrossReference_3_2_0() { return cPredicatPredicatCrossReference_3_2_0; }

		//EString
		public RuleCall getPredicatPredicatEStringParserRuleCall_3_2_0_1() { return cPredicatPredicatEStringParserRuleCall_3_2_0_1; }

		//("," predicat+=[Predicat|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//predicat+=[Predicat|EString]
		public Assignment getPredicatAssignment_3_3_1() { return cPredicatAssignment_3_3_1; }

		//[Predicat|EString]
		public CrossReference getPredicatPredicatCrossReference_3_3_1_0() { return cPredicatPredicatCrossReference_3_3_1_0; }

		//EString
		public RuleCall getPredicatPredicatEStringParserRuleCall_3_3_1_0_1() { return cPredicatPredicatEStringParserRuleCall_3_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_3_4() { return cRightParenthesisKeyword_3_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class DateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Date");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDayKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDayAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDayEIntegerObjectParserRuleCall_3_1_0 = (RuleCall)cDayAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMonthKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMonthAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMonthMonthEnumRuleCall_4_1_0 = (RuleCall)cMonthAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Date:
		//	{Date} "Date" "{" ("day" day=EIntegerObject)? ("month" month=Month)? "}";
		public ParserRule getRule() { return rule; }

		//{Date} "Date" "{" ("day" day=EIntegerObject)? ("month" month=Month)? "}"
		public Group getGroup() { return cGroup; }

		//{Date}
		public Action getDateAction_0() { return cDateAction_0; }

		//"Date"
		public Keyword getDateKeyword_1() { return cDateKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("day" day=EIntegerObject)?
		public Group getGroup_3() { return cGroup_3; }

		//"day"
		public Keyword getDayKeyword_3_0() { return cDayKeyword_3_0; }

		//day=EIntegerObject
		public Assignment getDayAssignment_3_1() { return cDayAssignment_3_1; }

		//EIntegerObject
		public RuleCall getDayEIntegerObjectParserRuleCall_3_1_0() { return cDayEIntegerObjectParserRuleCall_3_1_0; }

		//("month" month=Month)?
		public Group getGroup_4() { return cGroup_4; }

		//"month"
		public Keyword getMonthKeyword_4_0() { return cMonthKeyword_4_0; }

		//month=Month
		public Assignment getMonthAssignment_4_1() { return cMonthAssignment_4_1; }

		//Month
		public RuleCall getMonthMonthEnumRuleCall_4_1_0() { return cMonthMonthEnumRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class Atelier_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Atelier_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAtelierAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAtelierKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActivityKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActivityAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cActivityActivityCrossReference_3_1_0 = (CrossReference)cActivityAssignment_3_1.eContents().get(0);
		private final RuleCall cActivityActivityEStringParserRuleCall_3_1_0_1 = (RuleCall)cActivityActivityCrossReference_3_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Atelier_Impl returns exploitation::Atelier:
		//	{exploitation::Atelier} "Atelier" "{" ("activity" activity=[Activity|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{exploitation::Atelier} "Atelier" "{" ("activity" activity=[Activity|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{exploitation::Atelier}
		public Action getAtelierAction_0() { return cAtelierAction_0; }

		//"Atelier"
		public Keyword getAtelierKeyword_1() { return cAtelierKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("activity" activity=[Activity|EString])?
		public Group getGroup_3() { return cGroup_3; }

		//"activity"
		public Keyword getActivityKeyword_3_0() { return cActivityKeyword_3_0; }

		//activity=[Activity|EString]
		public Assignment getActivityAssignment_3_1() { return cActivityAssignment_3_1; }

		//[Activity|EString]
		public CrossReference getActivityActivityCrossReference_3_1_0() { return cActivityActivityCrossReference_3_1_0; }

		//EString
		public RuleCall getActivityActivityEStringParserRuleCall_3_1_0_1() { return cActivityActivityEStringParserRuleCall_3_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class EIntegerObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EIntegerObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EIntegerObject returns ecore::EIntegerObject:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class ResourceTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ResourceType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cResourceTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cResourceTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cResourceKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cResourceAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cResourceRessourceCrossReference_4_1_0 = (CrossReference)cResourceAssignment_4_1.eContents().get(0);
		private final RuleCall cResourceRessourceEStringParserRuleCall_4_1_0_1 = (RuleCall)cResourceRessourceCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ResourceType:
		//	{ResourceType} "ResourceType" name=EString "{" ("resource" resource=[exploitation::Ressource|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{ResourceType} "ResourceType" name=EString "{" ("resource" resource=[exploitation::Ressource|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{ResourceType}
		public Action getResourceTypeAction_0() { return cResourceTypeAction_0; }

		//"ResourceType"
		public Keyword getResourceTypeKeyword_1() { return cResourceTypeKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("resource" resource=[exploitation::Ressource|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"resource"
		public Keyword getResourceKeyword_4_0() { return cResourceKeyword_4_0; }

		//resource=[exploitation::Ressource|EString]
		public Assignment getResourceAssignment_4_1() { return cResourceAssignment_4_1; }

		//[exploitation::Ressource|EString]
		public CrossReference getResourceRessourceCrossReference_4_1_0() { return cResourceRessourceCrossReference_4_1_0; }

		//EString
		public RuleCall getResourceRessourceEStringParserRuleCall_4_1_0_1() { return cResourceRessourceEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class RessourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Ressource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRessourceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRessourceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cResourceTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cResourceTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cResourceTypeResourceTypeCrossReference_4_1_0 = (CrossReference)cResourceTypeAssignment_4_1.eContents().get(0);
		private final RuleCall cResourceTypeResourceTypeEStringParserRuleCall_4_1_0_1 = (RuleCall)cResourceTypeResourceTypeCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Ressource returns exploitation::Ressource:
		//	{exploitation::Ressource} "Ressource" name=EString "{" ("resourceType" resourceType=[ResourceType|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{exploitation::Ressource} "Ressource" name=EString "{" ("resourceType" resourceType=[ResourceType|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{exploitation::Ressource}
		public Action getRessourceAction_0() { return cRessourceAction_0; }

		//"Ressource"
		public Keyword getRessourceKeyword_1() { return cRessourceKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("resourceType" resourceType=[ResourceType|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"resourceType"
		public Keyword getResourceTypeKeyword_4_0() { return cResourceTypeKeyword_4_0; }

		//resourceType=[ResourceType|EString]
		public Assignment getResourceTypeAssignment_4_1() { return cResourceTypeAssignment_4_1; }

		//[ResourceType|EString]
		public CrossReference getResourceTypeResourceTypeCrossReference_4_1_0() { return cResourceTypeResourceTypeCrossReference_4_1_0; }

		//EString
		public RuleCall getResourceTypeResourceTypeEStringParserRuleCall_4_1_0_1() { return cResourceTypeResourceTypeEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class PredicatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Predicat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPredicatAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPredicatKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Predicat:
		//	{Predicat} "Predicat";
		public ParserRule getRule() { return rule; }

		//{Predicat} "Predicat"
		public Group getGroup() { return cGroup; }

		//{Predicat}
		public Action getPredicatAction_0() { return cPredicatAction_0; }

		//"Predicat"
		public Keyword getPredicatKeyword_1() { return cPredicatKeyword_1; }
	}

	public class ElevageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Elevage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cElevageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cElevageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAnimalsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAnimalsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAnimalsAnimalsEnumRuleCall_3_1_0 = (RuleCall)cAnimalsAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActivityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActivityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cActivityActivityCrossReference_4_1_0 = (CrossReference)cActivityAssignment_4_1.eContents().get(0);
		private final RuleCall cActivityActivityEStringParserRuleCall_4_1_0_1 = (RuleCall)cActivityActivityCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Elevage returns exploitation::Elevage:
		//	{exploitation::Elevage} "Elevage" "{" ("animals" animals=Animals)? ("activity" activity=[Activity|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{exploitation::Elevage} "Elevage" "{" ("animals" animals=Animals)? ("activity" activity=[Activity|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{exploitation::Elevage}
		public Action getElevageAction_0() { return cElevageAction_0; }

		//"Elevage"
		public Keyword getElevageKeyword_1() { return cElevageKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("animals" animals=Animals)?
		public Group getGroup_3() { return cGroup_3; }

		//"animals"
		public Keyword getAnimalsKeyword_3_0() { return cAnimalsKeyword_3_0; }

		//animals=Animals
		public Assignment getAnimalsAssignment_3_1() { return cAnimalsAssignment_3_1; }

		//Animals
		public RuleCall getAnimalsAnimalsEnumRuleCall_3_1_0() { return cAnimalsAnimalsEnumRuleCall_3_1_0; }

		//("activity" activity=[Activity|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"activity"
		public Keyword getActivityKeyword_4_0() { return cActivityKeyword_4_0; }

		//activity=[Activity|EString]
		public Assignment getActivityAssignment_4_1() { return cActivityAssignment_4_1; }

		//[Activity|EString]
		public CrossReference getActivityActivityCrossReference_4_1_0() { return cActivityActivityCrossReference_4_1_0; }

		//EString
		public RuleCall getActivityActivityEStringParserRuleCall_4_1_0_1() { return cActivityActivityEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class CultureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Culture");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCultureAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCultureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCerealsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCerealsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCerealsCerealEnumRuleCall_3_1_0 = (RuleCall)cCerealsAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActivityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActivityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cActivityActivityCrossReference_4_1_0 = (CrossReference)cActivityAssignment_4_1.eContents().get(0);
		private final RuleCall cActivityActivityEStringParserRuleCall_4_1_0_1 = (RuleCall)cActivityActivityCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Culture returns exploitation::Culture:
		//	{exploitation::Culture} "Culture" "{" ("cereals" cereals=Cereal)? ("activity" activity=[Activity|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{exploitation::Culture} "Culture" "{" ("cereals" cereals=Cereal)? ("activity" activity=[Activity|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{exploitation::Culture}
		public Action getCultureAction_0() { return cCultureAction_0; }

		//"Culture"
		public Keyword getCultureKeyword_1() { return cCultureKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("cereals" cereals=Cereal)?
		public Group getGroup_3() { return cGroup_3; }

		//"cereals"
		public Keyword getCerealsKeyword_3_0() { return cCerealsKeyword_3_0; }

		//cereals=Cereal
		public Assignment getCerealsAssignment_3_1() { return cCerealsAssignment_3_1; }

		//Cereal
		public RuleCall getCerealsCerealEnumRuleCall_3_1_0() { return cCerealsCerealEnumRuleCall_3_1_0; }

		//("activity" activity=[Activity|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"activity"
		public Keyword getActivityKeyword_4_0() { return cActivityKeyword_4_0; }

		//activity=[Activity|EString]
		public Assignment getActivityAssignment_4_1() { return cActivityAssignment_4_1; }

		//[Activity|EString]
		public CrossReference getActivityActivityCrossReference_4_1_0() { return cActivityActivityCrossReference_4_1_0; }

		//EString
		public RuleCall getActivityActivityEStringParserRuleCall_4_1_0_1() { return cActivityActivityEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	public class PeriodiciteElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Periodicite");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDailyEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDailyDailyKeyword_0_0 = (Keyword)cDailyEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWeeklyEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWeeklyWeeklyKeyword_1_0 = (Keyword)cWeeklyEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMonthlyEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMonthlyMonthlyKeyword_2_0 = (Keyword)cMonthlyEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Periodicite:
		//	Daily | Weekly | Monthly;
		public EnumRule getRule() { return rule; }

		//Daily | Weekly | Monthly
		public Alternatives getAlternatives() { return cAlternatives; }

		//Daily
		public EnumLiteralDeclaration getDailyEnumLiteralDeclaration_0() { return cDailyEnumLiteralDeclaration_0; }

		//"Daily"
		public Keyword getDailyDailyKeyword_0_0() { return cDailyDailyKeyword_0_0; }

		//Weekly
		public EnumLiteralDeclaration getWeeklyEnumLiteralDeclaration_1() { return cWeeklyEnumLiteralDeclaration_1; }

		//"Weekly"
		public Keyword getWeeklyWeeklyKeyword_1_0() { return cWeeklyWeeklyKeyword_1_0; }

		//Monthly
		public EnumLiteralDeclaration getMonthlyEnumLiteralDeclaration_2() { return cMonthlyEnumLiteralDeclaration_2; }

		//"Monthly"
		public Keyword getMonthlyMonthlyKeyword_2_0() { return cMonthlyMonthlyKeyword_2_0; }
	}

	public class ActivitesElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Activites");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLabourEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLabourLabourKeyword_0_0 = (Keyword)cLabourEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSemisEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSemisSemisKeyword_1_0 = (Keyword)cSemisEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cIrrigatgionEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cIrrigatgionIrrigatgionKeyword_2_0 = (Keyword)cIrrigatgionEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFertilisationEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFertilisationFertilisationKeyword_3_0 = (Keyword)cFertilisationEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cRecolteEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cRecolteRecolteKeyword_4_0 = (Keyword)cRecolteEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cALIMENTATIONEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cALIMENTATIONALIMENTATIONKeyword_5_0 = (Keyword)cALIMENTATIONEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cTraiteEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cTraiteTraiteKeyword_6_0 = (Keyword)cTraiteEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cSurveillanceagnelageEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cSurveillanceagnelageSurveillanceagnelageKeyword_7_0 = (Keyword)cSurveillanceagnelageEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cSurveillangevelageEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cSurveillangevelageSurveillangevelageKeyword_8_0 = (Keyword)cSurveillangevelageEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum Activites:
		//	labour | semis | irrigatgion | fertilisation | recolte | ALIMENTATION | traite | surveillanceagnelage |
		//	surveillangevelage;
		public EnumRule getRule() { return rule; }

		//labour | semis | irrigatgion | fertilisation | recolte | ALIMENTATION | traite | surveillanceagnelage |
		//surveillangevelage
		public Alternatives getAlternatives() { return cAlternatives; }

		//labour
		public EnumLiteralDeclaration getLabourEnumLiteralDeclaration_0() { return cLabourEnumLiteralDeclaration_0; }

		//"labour"
		public Keyword getLabourLabourKeyword_0_0() { return cLabourLabourKeyword_0_0; }

		//semis
		public EnumLiteralDeclaration getSemisEnumLiteralDeclaration_1() { return cSemisEnumLiteralDeclaration_1; }

		//"semis"
		public Keyword getSemisSemisKeyword_1_0() { return cSemisSemisKeyword_1_0; }

		//irrigatgion
		public EnumLiteralDeclaration getIrrigatgionEnumLiteralDeclaration_2() { return cIrrigatgionEnumLiteralDeclaration_2; }

		//"irrigatgion"
		public Keyword getIrrigatgionIrrigatgionKeyword_2_0() { return cIrrigatgionIrrigatgionKeyword_2_0; }

		//fertilisation
		public EnumLiteralDeclaration getFertilisationEnumLiteralDeclaration_3() { return cFertilisationEnumLiteralDeclaration_3; }

		//"fertilisation"
		public Keyword getFertilisationFertilisationKeyword_3_0() { return cFertilisationFertilisationKeyword_3_0; }

		//recolte
		public EnumLiteralDeclaration getRecolteEnumLiteralDeclaration_4() { return cRecolteEnumLiteralDeclaration_4; }

		//"recolte"
		public Keyword getRecolteRecolteKeyword_4_0() { return cRecolteRecolteKeyword_4_0; }

		//ALIMENTATION
		public EnumLiteralDeclaration getALIMENTATIONEnumLiteralDeclaration_5() { return cALIMENTATIONEnumLiteralDeclaration_5; }

		//"ALIMENTATION"
		public Keyword getALIMENTATIONALIMENTATIONKeyword_5_0() { return cALIMENTATIONALIMENTATIONKeyword_5_0; }

		//traite
		public EnumLiteralDeclaration getTraiteEnumLiteralDeclaration_6() { return cTraiteEnumLiteralDeclaration_6; }

		//"traite"
		public Keyword getTraiteTraiteKeyword_6_0() { return cTraiteTraiteKeyword_6_0; }

		//surveillanceagnelage
		public EnumLiteralDeclaration getSurveillanceagnelageEnumLiteralDeclaration_7() { return cSurveillanceagnelageEnumLiteralDeclaration_7; }

		//"surveillanceagnelage"
		public Keyword getSurveillanceagnelageSurveillanceagnelageKeyword_7_0() { return cSurveillanceagnelageSurveillanceagnelageKeyword_7_0; }

		//surveillangevelage
		public EnumLiteralDeclaration getSurveillangevelageEnumLiteralDeclaration_8() { return cSurveillangevelageEnumLiteralDeclaration_8; }

		//"surveillangevelage"
		public Keyword getSurveillangevelageSurveillangevelageKeyword_8_0() { return cSurveillangevelageSurveillangevelageKeyword_8_0; }
	}

	public class MonthElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Month");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cJanuaryEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cJanuaryJanuaryKeyword_0_0 = (Keyword)cJanuaryEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFebruaryEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFebruaryFebruaryKeyword_1_0 = (Keyword)cFebruaryEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMarchEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMarchMarchKeyword_2_0 = (Keyword)cMarchEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cAprilEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cAprilAprilKeyword_3_0 = (Keyword)cAprilEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cMayEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cMayMayKeyword_4_0 = (Keyword)cMayEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cJuneEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cJuneJuneKeyword_5_0 = (Keyword)cJuneEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cJulyEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cJulyJulyKeyword_6_0 = (Keyword)cJulyEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cAugustEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cAugustAugustKeyword_7_0 = (Keyword)cAugustEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cSeptemberEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cSeptemberSeptemberKeyword_8_0 = (Keyword)cSeptemberEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cOctoberEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cOctoberOctoberKeyword_9_0 = (Keyword)cOctoberEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cNovemberEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cNovemberNovemberKeyword_10_0 = (Keyword)cNovemberEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cDecemberEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cDecemberDecemberKeyword_11_0 = (Keyword)cDecemberEnumLiteralDeclaration_11.eContents().get(0);
		
		//enum Month:
		//	January | February | March | April | May | June | July | August | September | October | November | December;
		public EnumRule getRule() { return rule; }

		//January | February | March | April | May | June | July | August | September | October | November | December
		public Alternatives getAlternatives() { return cAlternatives; }

		//January
		public EnumLiteralDeclaration getJanuaryEnumLiteralDeclaration_0() { return cJanuaryEnumLiteralDeclaration_0; }

		//"January"
		public Keyword getJanuaryJanuaryKeyword_0_0() { return cJanuaryJanuaryKeyword_0_0; }

		//February
		public EnumLiteralDeclaration getFebruaryEnumLiteralDeclaration_1() { return cFebruaryEnumLiteralDeclaration_1; }

		//"February"
		public Keyword getFebruaryFebruaryKeyword_1_0() { return cFebruaryFebruaryKeyword_1_0; }

		//March
		public EnumLiteralDeclaration getMarchEnumLiteralDeclaration_2() { return cMarchEnumLiteralDeclaration_2; }

		//"March"
		public Keyword getMarchMarchKeyword_2_0() { return cMarchMarchKeyword_2_0; }

		//April
		public EnumLiteralDeclaration getAprilEnumLiteralDeclaration_3() { return cAprilEnumLiteralDeclaration_3; }

		//"April"
		public Keyword getAprilAprilKeyword_3_0() { return cAprilAprilKeyword_3_0; }

		//May
		public EnumLiteralDeclaration getMayEnumLiteralDeclaration_4() { return cMayEnumLiteralDeclaration_4; }

		//"May"
		public Keyword getMayMayKeyword_4_0() { return cMayMayKeyword_4_0; }

		//June
		public EnumLiteralDeclaration getJuneEnumLiteralDeclaration_5() { return cJuneEnumLiteralDeclaration_5; }

		//"June"
		public Keyword getJuneJuneKeyword_5_0() { return cJuneJuneKeyword_5_0; }

		//July
		public EnumLiteralDeclaration getJulyEnumLiteralDeclaration_6() { return cJulyEnumLiteralDeclaration_6; }

		//"July"
		public Keyword getJulyJulyKeyword_6_0() { return cJulyJulyKeyword_6_0; }

		//August
		public EnumLiteralDeclaration getAugustEnumLiteralDeclaration_7() { return cAugustEnumLiteralDeclaration_7; }

		//"August"
		public Keyword getAugustAugustKeyword_7_0() { return cAugustAugustKeyword_7_0; }

		//September
		public EnumLiteralDeclaration getSeptemberEnumLiteralDeclaration_8() { return cSeptemberEnumLiteralDeclaration_8; }

		//"September"
		public Keyword getSeptemberSeptemberKeyword_8_0() { return cSeptemberSeptemberKeyword_8_0; }

		//October
		public EnumLiteralDeclaration getOctoberEnumLiteralDeclaration_9() { return cOctoberEnumLiteralDeclaration_9; }

		//"October"
		public Keyword getOctoberOctoberKeyword_9_0() { return cOctoberOctoberKeyword_9_0; }

		//November
		public EnumLiteralDeclaration getNovemberEnumLiteralDeclaration_10() { return cNovemberEnumLiteralDeclaration_10; }

		//"November"
		public Keyword getNovemberNovemberKeyword_10_0() { return cNovemberNovemberKeyword_10_0; }

		//December
		public EnumLiteralDeclaration getDecemberEnumLiteralDeclaration_11() { return cDecemberEnumLiteralDeclaration_11; }

		//"December"
		public Keyword getDecemberDecemberKeyword_11_0() { return cDecemberDecemberKeyword_11_0; }
	}

	public class AnimalsElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Animals");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOvinEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOvinOvinKeyword_0_0 = (Keyword)cOvinEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBovinEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBovinBovinKeyword_1_0 = (Keyword)cBovinEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Animals returns exploitation::Animals:
		//	Ovin | Bovin;
		public EnumRule getRule() { return rule; }

		//Ovin | Bovin
		public Alternatives getAlternatives() { return cAlternatives; }

		//Ovin
		public EnumLiteralDeclaration getOvinEnumLiteralDeclaration_0() { return cOvinEnumLiteralDeclaration_0; }

		//"Ovin"
		public Keyword getOvinOvinKeyword_0_0() { return cOvinOvinKeyword_0_0; }

		//Bovin
		public EnumLiteralDeclaration getBovinEnumLiteralDeclaration_1() { return cBovinEnumLiteralDeclaration_1; }

		//"Bovin"
		public Keyword getBovinBovinKeyword_1_0() { return cBovinBovinKeyword_1_0; }
	}

	public class CerealElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Cereal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCornEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCornCornKeyword_0_0 = (Keyword)cCornEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWheatEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWheatWheatKeyword_1_0 = (Keyword)cWheatEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSorghumEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSorghumSorghumKeyword_2_0 = (Keyword)cSorghumEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Cereal returns exploitation::Cereal:
		//	Corn | Wheat | Sorghum;
		public EnumRule getRule() { return rule; }

		//Corn | Wheat | Sorghum
		public Alternatives getAlternatives() { return cAlternatives; }

		//Corn
		public EnumLiteralDeclaration getCornEnumLiteralDeclaration_0() { return cCornEnumLiteralDeclaration_0; }

		//"Corn"
		public Keyword getCornCornKeyword_0_0() { return cCornCornKeyword_0_0; }

		//Wheat
		public EnumLiteralDeclaration getWheatEnumLiteralDeclaration_1() { return cWheatEnumLiteralDeclaration_1; }

		//"Wheat"
		public Keyword getWheatWheatKeyword_1_0() { return cWheatWheatKeyword_1_0; }

		//Sorghum
		public EnumLiteralDeclaration getSorghumEnumLiteralDeclaration_2() { return cSorghumEnumLiteralDeclaration_2; }

		//"Sorghum"
		public Keyword getSorghumSorghumKeyword_2_0() { return cSorghumSorghumKeyword_2_0; }
	}
	
	private ActivityElements pActivity;
	private AtelierElements pAtelier;
	private PeriodiciteElements unknownRulePeriodicite;
	private Res_AllocElements pRes_Alloc;
	private RuleElements pRule;
	private DateElements pDate;
	private Atelier_ImplElements pAtelier_Impl;
	private ActivitesElements unknownRuleActivites;
	private EIntegerObjectElements pEIntegerObject;
	private ResourceTypeElements pResourceType;
	private EStringElements pEString;
	private RessourceElements pRessource;
	private PredicatElements pPredicat;
	private MonthElements unknownRuleMonth;
	private ElevageElements pElevage;
	private CultureElements pCulture;
	private AnimalsElements unknownRuleAnimals;
	private CerealElements unknownRuleCereal;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Activity:
	//	("Activity" "{" ("periodicite" periodicite=Periodicite)? ("activites" activites=Activites) ("atelier" "("
	//	atelier+=[exploitation::Atelier|EString] ("," atelier+=[exploitation::Atelier|EString])* ")")? ("res_alloc" "{"
	//	res_alloc+=Res_Alloc ("," res_alloc+=Res_Alloc)* "}")? ("rule" "{" rule+=Rule ("," rule+=Rule)* "}")? "fin" fin=Date
	//	"debut" debut=Date "}")*;
	public ActivityElements getActivityAccess() {
		return (pActivity != null) ? pActivity : (pActivity = new ActivityElements());
	}
	
	public ParserRule getActivityRule() {
		return getActivityAccess().getRule();
	}

	//Atelier returns exploitation::Atelier:
	//	Atelier_Impl | Elevage | Culture;
	public AtelierElements getAtelierAccess() {
		return (pAtelier != null) ? pAtelier : (pAtelier = new AtelierElements());
	}
	
	public ParserRule getAtelierRule() {
		return getAtelierAccess().getRule();
	}

	//enum Periodicite:
	//	Daily | Weekly | Monthly;
	public PeriodiciteElements getPeriodiciteAccess() {
		return (unknownRulePeriodicite != null) ? unknownRulePeriodicite : (unknownRulePeriodicite = new PeriodiciteElements());
	}
	
	public EnumRule getPeriodiciteRule() {
		return getPeriodiciteAccess().getRule();
	}

	//Res_Alloc:
	//	{Res_Alloc} "Res_Alloc" "{" ("duration" duration=EIntegerObject)? ("res_type" res_type=ResourceType)? "}";
	public Res_AllocElements getRes_AllocAccess() {
		return (pRes_Alloc != null) ? pRes_Alloc : (pRes_Alloc = new Res_AllocElements());
	}
	
	public ParserRule getRes_AllocRule() {
		return getRes_AllocAccess().getRule();
	}

	//Rule:
	//	{Rule} "Rule" "{" ("predicat" "(" predicat+=[Predicat|EString] ("," predicat+=[Predicat|EString])* ")")? "}";
	public RuleElements getRuleAccess() {
		return (pRule != null) ? pRule : (pRule = new RuleElements());
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}

	//Date:
	//	{Date} "Date" "{" ("day" day=EIntegerObject)? ("month" month=Month)? "}";
	public DateElements getDateAccess() {
		return (pDate != null) ? pDate : (pDate = new DateElements());
	}
	
	public ParserRule getDateRule() {
		return getDateAccess().getRule();
	}

	//Atelier_Impl returns exploitation::Atelier:
	//	{exploitation::Atelier} "Atelier" "{" ("activity" activity=[Activity|EString])? "}";
	public Atelier_ImplElements getAtelier_ImplAccess() {
		return (pAtelier_Impl != null) ? pAtelier_Impl : (pAtelier_Impl = new Atelier_ImplElements());
	}
	
	public ParserRule getAtelier_ImplRule() {
		return getAtelier_ImplAccess().getRule();
	}

	//enum Activites:
	//	labour | semis | irrigatgion | fertilisation | recolte | ALIMENTATION | traite | surveillanceagnelage |
	//	surveillangevelage;
	public ActivitesElements getActivitesAccess() {
		return (unknownRuleActivites != null) ? unknownRuleActivites : (unknownRuleActivites = new ActivitesElements());
	}
	
	public EnumRule getActivitesRule() {
		return getActivitesAccess().getRule();
	}

	//EIntegerObject returns ecore::EIntegerObject:
	//	"-"? INT;
	public EIntegerObjectElements getEIntegerObjectAccess() {
		return (pEIntegerObject != null) ? pEIntegerObject : (pEIntegerObject = new EIntegerObjectElements());
	}
	
	public ParserRule getEIntegerObjectRule() {
		return getEIntegerObjectAccess().getRule();
	}

	//ResourceType:
	//	{ResourceType} "ResourceType" name=EString "{" ("resource" resource=[exploitation::Ressource|EString])? "}";
	public ResourceTypeElements getResourceTypeAccess() {
		return (pResourceType != null) ? pResourceType : (pResourceType = new ResourceTypeElements());
	}
	
	public ParserRule getResourceTypeRule() {
		return getResourceTypeAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Ressource returns exploitation::Ressource:
	//	{exploitation::Ressource} "Ressource" name=EString "{" ("resourceType" resourceType=[ResourceType|EString])? "}";
	public RessourceElements getRessourceAccess() {
		return (pRessource != null) ? pRessource : (pRessource = new RessourceElements());
	}
	
	public ParserRule getRessourceRule() {
		return getRessourceAccess().getRule();
	}

	//Predicat:
	//	{Predicat} "Predicat";
	public PredicatElements getPredicatAccess() {
		return (pPredicat != null) ? pPredicat : (pPredicat = new PredicatElements());
	}
	
	public ParserRule getPredicatRule() {
		return getPredicatAccess().getRule();
	}

	//enum Month:
	//	January | February | March | April | May | June | July | August | September | October | November | December;
	public MonthElements getMonthAccess() {
		return (unknownRuleMonth != null) ? unknownRuleMonth : (unknownRuleMonth = new MonthElements());
	}
	
	public EnumRule getMonthRule() {
		return getMonthAccess().getRule();
	}

	//Elevage returns exploitation::Elevage:
	//	{exploitation::Elevage} "Elevage" "{" ("animals" animals=Animals)? ("activity" activity=[Activity|EString])? "}";
	public ElevageElements getElevageAccess() {
		return (pElevage != null) ? pElevage : (pElevage = new ElevageElements());
	}
	
	public ParserRule getElevageRule() {
		return getElevageAccess().getRule();
	}

	//Culture returns exploitation::Culture:
	//	{exploitation::Culture} "Culture" "{" ("cereals" cereals=Cereal)? ("activity" activity=[Activity|EString])? "}";
	public CultureElements getCultureAccess() {
		return (pCulture != null) ? pCulture : (pCulture = new CultureElements());
	}
	
	public ParserRule getCultureRule() {
		return getCultureAccess().getRule();
	}

	//enum Animals returns exploitation::Animals:
	//	Ovin | Bovin;
	public AnimalsElements getAnimalsAccess() {
		return (unknownRuleAnimals != null) ? unknownRuleAnimals : (unknownRuleAnimals = new AnimalsElements());
	}
	
	public EnumRule getAnimalsRule() {
		return getAnimalsAccess().getRule();
	}

	//enum Cereal returns exploitation::Cereal:
	//	Corn | Wheat | Sorghum;
	public CerealElements getCerealAccess() {
		return (unknownRuleCereal != null) ? unknownRuleCereal : (unknownRuleCereal = new CerealElements());
	}
	
	public EnumRule getCerealRule() {
		return getCerealAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
