/**
 *
 * $Id$
 */
package activity.validation;

import activity.Month;

/**
 * A sample validator interface for {@link activity.Date}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DateValidator {
	boolean validate();

	boolean validateDay(Integer value);
	boolean validateMonth(Month value);
}
