/**
 *
 * $Id$
 */
package activity.validation;

import activity.Activity;
import activity.Model;
import activity.ResourceType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link activity.Model}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelValidator {
	boolean validate();

	boolean validateEReference0(Model value);
	boolean validateActivity(EList<Activity> value);
	boolean validateRes_type(ResourceType value);
}
