<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activity" nsURI="http://activity/1.0" nsPrefix="activity">
  <eClassifiers xsi:type="ecore:EClass" name="ResourceType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="ecore:EClass Exploitation.ecore#//Ressource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicat"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicat" upperBound="-1"
        eType="#//Predicat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="periodicite" eType="#//Periodicite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="res_alloc" upperBound="-1"
        eType="#//Res_Alloc" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fin" lowerBound="1" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="debut" lowerBound="1" eType="#//Date"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atelier" upperBound="-1"
        eType="ecore:EClass Exploitation.ecore#//Atelier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
        eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="res_type" eType="#//ResourceType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Date">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" eType="#//Month"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Res_Alloc">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="res_type" eType="#//ResourceType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Month">
    <eLiterals name="January"/>
    <eLiterals name="February" value="1"/>
    <eLiterals name="March" value="2"/>
    <eLiterals name="April" value="3"/>
    <eLiterals name="May" value="4"/>
    <eLiterals name="June" value="5"/>
    <eLiterals name="July" value="6"/>
    <eLiterals name="August" value="7"/>
    <eLiterals name="September" value="8"/>
    <eLiterals name="October" value="9"/>
    <eLiterals name="November" value="10"/>
    <eLiterals name="December" value="11"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Periodicite">
    <eLiterals name="Daily"/>
    <eLiterals name="Weekly" value="1"/>
    <eLiterals name="Monthly" value="2"/>
  </eClassifiers>
</ecore:EPackage>
